In [ ]:
import pandas as pd

In [ ]:
def findHeavyAnimals(animals):
    animals = animals.query('weight > 100').sort_values(by='weight', ascending=False)[['name']]
    return animals

In [ ]:
# Пример DataFrame animals
data = {
    'name': ['Tatiana', 'Khaled', 'Alex', 'Jonathan', 'Stefan', 'Tommy'],
    'species': ['Snake', 'Giraffe', 'Leopard', 'Monkey', 'Bear', 'Panda'],
    'age': [98, 50, 6, 45, 100, 26],
    'weight': [464, 41, 328, 463, 50, 349]
}

animals = pd.DataFrame(data)
print(animals)
print()

pri
# Вызываем функцию для поиска тяжёлых животных
result = findHeavyAnimals(animals)
print(result)

NameError: name 'pd' is not defined